# -*- coding: utf-8 -*-
"""VeriBilimineGirişProje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHFERTu0ueB0ZMHa704NpXoCBzfl3g9w

**İçindekiler**   

* Veri temizleme ve hazırlama  

* Sızıntısız Öznitelik Mühendisliği (K-Fold Target Encoding & Bayesian Smoothing)  

* Keşifsel Veri Analizi (Sınıf Dağılımı ve Korelasyon Isı Haritası)  

* K-Means, Hiyerarşik Kümeleme, DBSCAN  

* YSA  

* KNN, Karar Ağacı, Random Forest, SVM, Naive Bayes  

* Tüm Algoritmaların Karşılaştırmalı Başarı Sıralaması  

* Hedef Değişken (Sınıf) Dağılımı Grafiği  

* 5 Katlı Cross-Validation


* Confusion Matrix Görselleri  


* ROC-AUC Eğrileri  


* Nihai Kapsamlı Performans Tablosu  


* Yayım Yılı Analizi (Dönemsel popülerlik trendleri)  


* Küme Profili Analizi (K-Means küme özellikleri)  


* Yeni Kitap Popülerlik Tahmin Sistemi


* Learning Curve / Öğrenme Eğrileri


* SMOTE Analizi

#Merve
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd, numpy as np, time, random
import matplotlib.pyplot as plt, seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, KFold

time.sleep(3)
df = pd.read_csv('/content/drive/MyDrive/books.csv', on_bad_lines='skip')
df.columns = df.columns.str.strip()
df = df[df['num_pages'] != 0]
df = df[df['average_rating'] >= 2.0]
df['ratings_count_log'] = np.log1p(df['ratings_count'])

#ÖZNİTELİK MÜHENDİSLİĞİ
df['populerlik'] = (df['average_rating'] >= 4.0).astype(int)
df['review_ratio'] = df['text_reviews_count'] / (df['ratings_count'] + 1)
df['pub_date_dt']  = pd.to_datetime(df['publication_date'], errors='coerce')
df['pub_year']     = df['pub_date_dt'].dt.year.fillna(df['pub_date_dt'].dt.year.median()).astype(int)
df['is_series']    = df['title'].str.contains(r'#\d|\(', regex=True).astype(int)
df['is_english']   = df['language_code'].str.startswith('en', na=False).astype(int)
df['author_main']  = df['authors'].str.split('-').str[0].str.split('/').str[0]
# VERİYİ BÖLER
df_train, df_test = train_test_split(df, test_size=0.2, random_state=42)

#K-FOLD TARGET ENCODING
def kfold_target_encoding(train_df, test_df, col, target='populerlik', n_splits=5, weight=15):
    global_mean = train_df[target].mean()
    train_encoded = pd.Series(index=train_df.index, dtype=float)
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

    for train_idx, val_idx in kf.split(train_df):
        X_tr, X_val = train_df.iloc[train_idx], train_df.iloc[val_idx]
        agg = X_tr.groupby(col)[target].agg(['count', 'mean'])
        smooth = (agg['count'] * agg['mean'] + weight * global_mean) / (agg['count'] + weight)
        train_encoded.iloc[val_idx] = X_val[col].map(smooth).fillna(global_mean).values

    # Test setine sadece eğitim setinin bilgisini aktarır
    agg_full = train_df.groupby(col)[target].agg(['count', 'mean'])
    smooth_full = (agg_full['count'] * agg_full['mean'] + weight * global_mean) / (agg_full['count'] + weight)
    test_encoded = test_df[col].map(smooth_full).fillna(global_mean).values

    return train_encoded, test_encoded, smooth_full, global_mean

df_train = df_train.copy(); df_test = df_test.copy()
df_train['publisher_success'], df_test['publisher_success'], smooth_pub, g_pub = kfold_target_encoding(df_train, df_test, 'publisher')
df_train['author_success'], df_test['author_success'], smooth_auth, g_auth = kfold_target_encoding(df_train, df_test, 'author_main')

# Kümeleme için tüm veri setine haritalama yapılır
df['publisher_success'] = df['publisher'].map(smooth_pub).fillna(g_pub)
df['author_success'] = df['author_main'].map(smooth_auth).fillna(g_auth)

feature_names = ['num_pages', 'ratings_count_log', 'text_reviews_count',
                 'review_ratio', 'pub_year', 'is_series', 'is_english',
                 'publisher_success', 'author_success']

X_train = df_train[feature_names]; y_train = df_train['populerlik']
X_test  = df_test[feature_names]; y_test  = df_test['populerlik']

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

cluster_scaler = StandardScaler()
X_cluster_scaled = cluster_scaler.fit_transform(df[feature_names])

print("Eğitim seti:", X_train.shape)
print("Sınıf Dağılımı:\n", df['populerlik'].value_counts())

corr = pd.DataFrame(X_train, columns=feature_names).corr()
plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, fmt='.3f', cmap='Reds', xticklabels=feature_names, yticklabels=feature_names)
plt.title("Özellikler Arası Korelasyon Isı Haritası", fontsize=13)
plt.tight_layout(); plt.show()

"""**K-Means**"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

inertia = []
for k in range(1, 10):
    km = KMeans(n_clusters=k, random_state=42, n_init=10); km.fit(X_cluster_scaled); inertia.append(km.inertia_)
plt.figure(figsize=(8, 4))
plt.plot(range(1,10), inertia, marker='o', color='purple', linestyle='--')
plt.title("Elbow Yöntemi", fontweight='bold'); plt.xlabel("k"); plt.ylabel("Inertia"); plt.grid(True, alpha=0.3); plt.show()

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
labels_kmeans = kmeans.fit_predict(X_cluster_scaled)
plt.figure(figsize=(8, 5))
plt.scatter(X_cluster_scaled[:,0], X_cluster_scaled[:,1], c=labels_kmeans, cmap='viridis', alpha=0.5, s=10)
plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], color='red', marker='X', s=200, label='Merkezler')
plt.title("K-Means Kümeleme Sonuçları"); plt.legend(); plt.show()
df['kmeans_cluster'] = labels_kmeans
score_kmeans = silhouette_score(X_cluster_scaled, labels_kmeans)
print(f"K-Means Silhouette Score: {score_kmeans:.4f}")

"""**Hiyerarşik Kümeleme**"""

from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage

linked = linkage(X_cluster_scaled[:200], method='ward')
plt.figure(figsize=(12, 6)); dendrogram(linked, leaf_rotation=90, leaf_font_size=8)
plt.title("Dendrogram — Hiyerarşik Kümeleme"); plt.show()
hc = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
labels_hc = hc.fit_predict(X_cluster_scaled)
df['hc_cluster'] = labels_hc
score_hc = silhouette_score(X_cluster_scaled, labels_hc)
print(f"Hiyerarşik Silhouette Score: {score_hc:.4f}")

"""**DBSCAN**"""

from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps=1.5, min_samples=5)
labels_dbscan = dbscan.fit_predict(X_cluster_scaled)
n_clusters_db = len(set(labels_dbscan)) - (1 if -1 in labels_dbscan else 0)
n_noise = list(labels_dbscan).count(-1)
print(f"DBSCAN Küme Sayısı: {n_clusters_db}, Gürültü: {n_noise}")
plt.figure(figsize=(8, 5))
plt.scatter(X_cluster_scaled[:,0], X_cluster_scaled[:,1], c=labels_dbscan, cmap='plasma', alpha=0.5, s=10)
plt.title("DBSCAN Kümeleme Analizi"); plt.show()
mask = labels_dbscan != -1
score_dbscan = silhouette_score(X_cluster_scaled[mask], labels_dbscan[mask]) if mask.sum() > 1 else None
if score_dbscan: print(f"DBSCAN Silhouette Score: {score_dbscan:.4f}")
df['dbscan_cluster'] = labels_dbscan

"""**YSA**"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score

np.random.seed(42); tf.random.set_seed(42); random.seed(42)

model = Sequential([
    Dense(16, input_shape=(len(feature_names),), activation='relu', kernel_regularizer=l2(0.01)),
    Dropout(0.4),
    Dense(8, activation='relu', kernel_regularizer=l2(0.01)),
    Dropout(0.4),
    Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history = model.fit(X_train, y_train, epochs=50, batch_size=32,
                    validation_data=(X_test, y_test), callbacks=[early_stop], verbose=0)
loss, accuracy_ysa = model.evaluate(X_test, y_test, verbose=0)
y_pred_ysa = (model.predict(X_test) > 0.5).astype("int32")
print(f"YSA Test Doğruluğu: {accuracy_ysa:.4f}")
print(classification_report(y_test, y_pred_ysa, target_names=['Popüler Değil (<4.0)', 'Popüler (>=4.0)']))

plt.figure(figsize=(10, 4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Eğitim'); plt.plot(history.history['val_accuracy'], label='Doğrulama')
plt.title("Doğruluk Eğrisi"); plt.legend(); plt.grid(True, alpha=0.3)
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Eğitim'); plt.plot(history.history['val_loss'], label='Doğrulama')
plt.title("Kayıp Eğrisi"); plt.legend(); plt.grid(True, alpha=0.3)
plt.tight_layout(); plt.show()

"""#Sinem"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
sonuclar = []

print("--- KNN Modeli Deneyleri ---")
for k in [3, 5, 7]:
    knn = KNeighborsClassifier(n_neighbors=k); knn.fit(X_train, y_train)
    acc = accuracy_score(y_test, knn.predict(X_test)); print(f"k={k} Doğruluk: {acc:.4f}")
    if k == 5:
        print(classification_report(y_test, knn.predict(X_test), target_names=['Popüler Değil', 'Popüler']))
        sonuclar.append(['KNN (k=5)', acc])

print("\n--- Karar Ağacı Deneyleri ---")
for crit in ['gini', 'entropy']:
    dt = DecisionTreeClassifier(criterion=crit, max_depth=5, random_state=42); dt.fit(X_train, y_train)
    acc = accuracy_score(y_test, dt.predict(X_test)); print(f"Kriter: {crit}, Doğruluk: {acc:.4f}")
    sonuclar.append([f'Karar Ağacı ({crit})', acc])

plt.figure(figsize=(20,10))
plot_tree(dt, feature_names=feature_names, class_names=['Popüler Değil','Popüler'], filled=True, rounded=True, fontsize=10)
plt.title("Karar Ağacı Dallanma Yapısı"); plt.show()

print("\n--- Random Forest ---")
rf = RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42); rf.fit(X_train, y_train)
acc_rf = accuracy_score(y_test, rf.predict(X_test)); print(f"RF Doğruluk: {acc_rf:.4f}")
sonuclar.append(['Random Forest', acc_rf])
plt.figure(figsize=(10,6)); sns.barplot(x=rf.feature_importances_, y=feature_names, palette='viridis')
plt.title("Özellik Önem Düzeyi (Random Forest)"); plt.show()

print("\n--- SVM Deneyleri ---")
for kernel in ['linear','rbf']:
    for c_val in [0.1, 1, 10]:
        svm = SVC(kernel=kernel, C=c_val, random_state=42); svm.fit(X_train, y_train)
        acc = accuracy_score(y_test, svm.predict(X_test))
        print(f"Kernel: {kernel:6} | C: {c_val:4} | Doğruluk: {acc:.4f}")
        if c_val == 1: sonuclar.append([f'SVM ({kernel})', acc])

print("\n--- Naive Bayes ---")
nb = GaussianNB(); nb.fit(X_train, y_train)
acc_nb = accuracy_score(y_test, nb.predict(X_test)); print(f"NB Doğruluk: {acc_nb:.4f}")
print(classification_report(y_test, nb.predict(X_test), target_names=['Popüler Değil','Popüler']))
sonuclar.append(['Naive Bayes', acc_nb])

"""Sonuçlar"""
df_sonuclar = pd.DataFrame(sonuclar, columns=['Algoritma','Doğruluk (Accuracy)'])
print(df_sonuclar.sort_values(by='Doğruluk (Accuracy)', ascending=False).to_string(index=False))

plt.figure(figsize=(8,5))
bars = plt.bar(['Popüler Değil','Popüler'], df['populerlik'].value_counts().sort_index().values, color=['#e74c3c','#27ae60'], edgecolor='black')
for b,v in zip(bars, df['populerlik'].value_counts().sort_index().values):
    plt.text(b.get_x()+b.get_width()/2, b.get_height()+50, f"{v}", ha='center', fontweight='bold')
plt.title("Hedef Değişken Dağılımı"); plt.tight_layout(); plt.show()

"""5 Katlı CV"""
from sklearn.model_selection import StratifiedKFold, cross_val_score
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
modeller_cv = {"KNN (k=5)": KNeighborsClassifier(n_neighbors=5), "Karar Ağacı": DecisionTreeClassifier(max_depth=5, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42), "SVM": SVC(kernel='rbf', C=1.0, random_state=42), "Naive Bayes": GaussianNB()}
cv_sonuclar = []
print("5 KATLI CV SONUÇLARI")
for ad, m in modeller_cv.items():
    skorlar = cross_val_score(m, X_train, y_train, cv=cv, scoring='accuracy')
    cv_sonuclar.append({'Algoritma': ad, 'CV Ort. Doğruluk': round(skorlar.mean(),4), 'Standart Sapma': round(skorlar.std(),4)})
    print(f"{ad:15s} → {skorlar.mean():.4f} ± {skorlar.std():.4f}")
print(pd.DataFrame(cv_sonuclar).sort_values(by='CV Ort. Doğruluk', ascending=False).to_string(index=False))

"""Confusion Matrix"""
sinif_adlari = ['Popüler Değil','Popüler']
fig, axes = plt.subplots(2,3, figsize=(16,10)); axes = axes.flatten()
modeller_cm = [("KNN (k=5)", KNeighborsClassifier(n_neighbors=5)),("Karar Ağacı", DecisionTreeClassifier(max_depth=5, random_state=42)),
    ("Random Forest", RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42)),("SVM", SVC(kernel='rbf', C=1.0, random_state=42)),("Naive Bayes", GaussianNB()),("YSA", None)]
for i,(ad,m) in enumerate(modeller_cm):
    if ad=="YSA": yp=(model.predict(X_test)>0.5).astype("int32")
    else: m.fit(X_train, y_train); yp=m.predict(X_test)
    ConfusionMatrixDisplay(confusion_matrix(y_test,yp), display_labels=sinif_adlari).plot(ax=axes[i], colorbar=False, cmap='Blues')
    axes[i].set_title(ad, fontweight='bold')
plt.suptitle("Confusion Matrix — Tüm Modeller", fontsize=16, fontweight='bold'); plt.tight_layout(); plt.show()

"""ROC-AUC"""
from sklearn.metrics import roc_auc_score, roc_curve
plt.figure(figsize=(9,6)); tablo_final = []
modeller_roc = [("KNN (k=5)", KNeighborsClassifier(n_neighbors=5)),("Karar Ağacı", DecisionTreeClassifier(max_depth=5, random_state=42)),
    ("Random Forest", RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42)),("SVM", SVC(kernel='rbf', C=1.0, probability=True, random_state=42)),("Naive Bayes", GaussianNB())]
for ad,m in modeller_roc:
    m.fit(X_train, y_train); yp=m.predict(X_test); yprob=m.predict_proba(X_test)[:,1]
    auc_val = roc_auc_score(y_test, yprob)
    cv_ort = next((r['CV Ort. Doğruluk'] for r in cv_sonuclar if r['Algoritma']==ad), "-")
    tablo_final.append([ad, round(accuracy_score(y_test,yp),4), round(precision_score(y_test,yp),4),
        round(recall_score(y_test,yp),4), round(f1_score(y_test,yp),4), round(auc_val,4), cv_ort])
    fpr,tpr,_ = roc_curve(y_test, yprob); plt.plot(fpr, tpr, label=f"{ad} (AUC={auc_val:.3f})", linewidth=2)

yprob_ysa = model.predict(X_test).ravel(); yp_ysa = (yprob_ysa>0.5).astype(int)
auc_ysa = roc_auc_score(y_test, yprob_ysa)
tablo_final.append(["YSA", round(accuracy_score(y_test,yp_ysa),4), round(precision_score(y_test,yp_ysa),4),
    round(recall_score(y_test,yp_ysa),4), round(f1_score(y_test,yp_ysa),4), round(auc_ysa,4), "-"])
fpr_y,tpr_y,_ = roc_curve(y_test, yprob_ysa)
plt.plot(fpr_y, tpr_y, label=f"YSA (AUC={auc_ysa:.3f})", linewidth=2, linestyle='--')
plt.plot([0,1],[0,1],'k--', alpha=0.4); plt.title("ROC Eğrileri"); plt.legend(fontsize=9); plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

df_final = pd.DataFrame(tablo_final, columns=['Algoritma','Accuracy','Precision','Recall','F1-Score','ROC-AUC','CV Ort.'])
print("\nNİHAİ PERFORMANS TABLOSU")
print(df_final.sort_values(by='ROC-AUC', ascending=False).to_string(index=False))
print(f"\nK-Means: {score_kmeans:.4f} | Hiyerarşik: {score_hc:.4f}", end="")
if score_dbscan: print(f" | DBSCAN: {score_dbscan:.4f}")
else: print(" | DBSCAN: Hesaplanamadı")

#YAYIM YILI ANALİZİ
df_yil = df[df['pub_year'] >= 1950].copy()
bins = [1950,1970,1980,1990,2000,2005,2010,2015,2020]
etiket = ['1950-70','1971-80','1981-90','1991-00','2001-05','2006-10','2011-15','2016-20']
df_yil['donem'] = pd.cut(df_yil['pub_year'], bins=bins, labels=etiket)
donem_ozet = df_yil.groupby('donem', observed=True)['average_rating'].agg(Kitap_Sayisi='count', Ort_Puan='mean').round(3)
print("Dönem Bazlı Özet:"); print(donem_ozet.to_string())

fig, axes = plt.subplots(1,3, figsize=(18,5))
donem_ozet['Ort_Puan'].plot(kind='bar', ax=axes[0], color='steelblue', edgecolor='black')
axes[0].set_title("Dönem Bazlı Ortalama Puan"); axes[0].set_ylim(3.85, 4.10)
donem_ozet['Kitap_Sayisi'].plot(kind='bar', ax=axes[1], color='coral', edgecolor='black')
axes[1].set_title("Dönem Bazlı Kitap Sayısı")
yil_ort = df_yil.groupby('pub_year')['average_rating'].mean()
axes[2].scatter(yil_ort.index, yil_ort.values, alpha=0.6, color='purple', s=30)
z = np.polyfit(yil_ort.index, yil_ort.values, 1)
axes[2].plot(yil_ort.index, np.poly1d(z)(yil_ort.index), 'r--', linewidth=2, label='Trend')
axes[2].set_title("Yıllık Puan Trendi"); axes[2].legend()
plt.suptitle("Yayım Yılı Analizi", fontweight='bold'); plt.tight_layout(); plt.show()
print(f"Kitap Sayısı <-> Puan Korelasyonu: {donem_ozet['Kitap_Sayisi'].corr(donem_ozet['Ort_Puan']):.4f}")

# KÜME PROFİLİ
df_profil = df.copy(); df_profil['kmeans_cluster'] = labels_kmeans
kume_profil = df_profil.groupby('kmeans_cluster', observed=True).agg(
    Kitap_Sayisi=('average_rating','count'), Ort_Puan=('average_rating','mean'),
    Ort_Sayfa=('num_pages','mean'), Ort_Degerlendirme=('ratings_count','mean'),
    Ort_Yorum=('text_reviews_count','mean')).round(2)
print("\nKüme Profili:"); print(kume_profil.to_string())

fig, axes = plt.subplots(1,3, figsize=(15,6))
df_profil.boxplot(column='average_rating', by='kmeans_cluster', ax=axes[0], grid=False)
df_profil.boxplot(column='ratings_count', by='kmeans_cluster', ax=axes[1], grid=False); axes[1].set_yscale('log')
df_profil.boxplot(column='num_pages', by='kmeans_cluster', ax=axes[2], grid=False)
plt.suptitle("K-Means Küme Profilleri", fontweight='bold'); plt.tight_layout(); plt.show()

# TAHMİN SİSTEMİ
tahmin_modelleri = {"KNN (k=5)": KNeighborsClassifier(n_neighbors=5), "Karar Ağacı": DecisionTreeClassifier(max_depth=5, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42),
    "SVM": SVC(kernel='rbf', C=1.0, probability=True, random_state=42), "Naive Bayes": GaussianNB()}
for ad, m in tahmin_modelleri.items(): m.fit(X_train, y_train)

def kitap_tahmin(sayfa, degerlendirme, yorum):
    from collections import Counter
    r_log = np.log1p(degerlendirme); rev_r = yorum/(degerlendirme+1)
    pub_yr = int(df['pub_year'].median()); is_ser = 0; is_eng = 1
    p_rate = g_pub; a_rate = g_auth
    yeni = scaler.transform([[sayfa, r_log, yorum, rev_r, pub_yr, is_ser, is_eng, p_rate, a_rate]])
    tahminler = []
    print(f"\nSayfa:{sayfa}, Değ:{degerlendirme}, Yorum:{yorum}")
    for ad, m in tahmin_modelleri.items():
        t = m.predict(yeni)[0]; tahminler.append(t)
        print(f"  {ad:<18} -> {'Popüler' if t==1 else 'Değil'}")
    ysa_t = int(model.predict(yeni)[0][0]>0.5); tahminler.append(ysa_t)
    print(f"  {'YSA':<18} -> {'Popüler' if ysa_t==1 else 'Değil'}")
    s = Counter(tahminler).most_common(1)[0]
    print(f"  Çoğunluk: {'Popüler' if s[0]==1 else 'Değil'} ({s[1]}/6)")

kitap_tahmin(600, 2000000, 50000)
kitap_tahmin(120, 150, 10)
kitap_tahmin(350, 15000, 800)

# LEARNING CURVE
from sklearn.model_selection import learning_curve
lc_m = {"SVM": SVC(kernel='rbf', C=1.0, random_state=42), "Random Forest": RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42),
    "KNN (k=5)": KNeighborsClassifier(n_neighbors=5)}
fig, axes = plt.subplots(1,3, figsize=(18,5)); renkler = ['steelblue','coral','green']
for idx,(ad,m) in enumerate(lc_m.items()):
    ts,tr_s,te_s = learning_curve(m, X_train, y_train, cv=5, train_sizes=np.linspace(0.1,1.0,10), scoring='accuracy', n_jobs=-1)
    axes[idx].plot(ts, tr_s.mean(1), 'o-', color=renkler[idx], label='Eğitim')
    axes[idx].plot(ts, te_s.mean(1), 's--', color=renkler[idx], alpha=0.6, label='Doğrulama')
    axes[idx].fill_between(ts, te_s.mean(1)-te_s.std(1), te_s.mean(1)+te_s.std(1), alpha=0.1, color=renkler[idx])
    axes[idx].set_title(ad, fontweight='bold'); axes[idx].legend(fontsize=9); axes[idx].grid(True, alpha=0.3)
    axes[idx].set_ylim(0.50, 0.90)
plt.suptitle("Learning Curve", fontweight='bold'); plt.tight_layout(); plt.show()

# SMOTE ANALİZİ
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
X_smote, y_smote = sm.fit_resample(X_train, y_train)

print(f"\n{'Algoritma':<20} {'Normal':>10} {'SMOTE':>10} {'Fark':>8}")
print("-"*52)
normal_m = {"KNN (k=5)": KNeighborsClassifier(n_neighbors=5), "Karar Ağacı": DecisionTreeClassifier(max_depth=5, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42),
    "SVM": SVC(kernel='rbf', C=1.0, random_state=42), "Naive Bayes": GaussianNB()}
for ad, m_n in normal_m.items():
    m_n.fit(X_train, y_train); n_acc = accuracy_score(y_test, m_n.predict(X_test))
    m_s = type(m_n)(**m_n.get_params()); m_s.fit(X_smote, y_smote); s_acc = accuracy_score(y_test, m_s.predict(X_test))
    fark = s_acc - n_acc; isaret = "+" if fark > 0 else ""
    print(f"{ad:<20} {n_acc:>10.4f} {s_acc:>10.4f} {isaret}{fark:>7.4f}")